# Generated by Django 4.1.5 on 2023-02-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Токен'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
