# Generated by Django 4.1.5 on 2023-01-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_record_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.SlugField(verbose_name='URL'),
        ),
    ]
