# Generated by Django 4.1.5 on 2023-02-02 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_record_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.SlugField(default='', verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.FloatField(default=1, verbose_name='Номер версии')),
                ('version_name', models.CharField(max_length=50, verbose_name='Название версии')),
                ('version_status', models.CharField(choices=[('active', 'активная'), ('inactive', 'неактивная')], default='inactive', max_length=10, verbose_name='текущая версия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Продукт')),
            ],
        ),
    ]
