# Generated by Django 4.1.5 on 2023-02-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_public_status', 'Can change public status'), ('change_description', 'Can change description'), ('change_category', 'Can change category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Опубликованно'),
        ),
    ]
