# Generated by Django 4.1.5 on 2023-02-07 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_options_product_is_public'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_is_public', 'Can change public status'), ('change_description_product', 'Can change description'), ('change_category_product', 'Can change category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
